### ISSUE TITLE
Gke cluster not creating with existing subnetwork

### ISSUE THREAD

**Issue by sarab321** [GoogleCloudPlatform/gke-network-policy-demo#21]
I am using the below network fields while creating gkecluster but it is throwing error that 
"Create cluster cannot be created with existing subnetwork"

	network            = "${google_compute_network.vpc.self_link}"
    subnetwork         = "${google_compute_subnetwork.gkesubnet.self_link}"

How to attach existing subnetwork while creating gkecluster

**Comment by thefirstofthe300** [comment]
Looks like this same question was asked [on StackOverflow](https://stackoverflow.com/questions/54837920/how-to-add-existing-subnetwork-for-gke-cluster-using-terraform)

I'm going to go ahead and close the issue since the code posted to Stackoverflow is not using this module.
